# Generated by Django 4.1.7 on 2023-03-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_tradingstep_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_buy', models.FloatField(verbose_name='Price Buy')),
                ('price_sell', models.FloatField(verbose_name='Price Sell')),
                ('value', models.FloatField(verbose_name='Token Value')),
                ('date_create_buy', models.DateTimeField(blank=True, null=True, verbose_name='Date And Time of Create Buy Order')),
                ('date_buy', models.DateTimeField(blank=True, null=True, verbose_name='Date And Time Buy')),
                ('date_sell', models.DateTimeField(blank=True, null=True, verbose_name='Date And Time Sell')),
                ('order_buy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Buy Order Id')),
                ('order_sell', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sell Order Id')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trades.tradingstep')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
