# Generated by Django 4.1.7 on 2023-03-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_sell',
        ),
    ]
