# Generated by Django 4.1.7 on 2023-03-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_order_date_create_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Pair Name'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingstep',
            unique_together={('pair', 'step')},
        ),
    ]
