# Generated by Django 4.1.7 on 2023-04-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_pair_name_alter_tradingstep_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_buy',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Buy Order Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_sell',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Sell Order Id'),
        ),
    ]
