# Generated by Django 4.1.7 on 2025-02-06 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0008_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Range",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.FloatField(verbose_name="Min Trade Value")),
                ("max_value", models.FloatField(verbose_name="Max Trade Value")),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="trades.pair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Range",
                "verbose_name_plural": "Ranges",
                "unique_together": {("pair", "min_value", "max_value")},
            },
        ),
    ]
